name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --verbose
    - name: Check
      run: cargo check --verbose
    - name: Run cargo fmt check
      run: cargo fmt -- --check
    - name: Run cargo audit
      run: cargo install cargo-audit && cargo audit
