name: Rust checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy Check
      run: cargo clippy --verbose
    - name: Testing
      run: cargo test --workspace --verbose
    - name: Format Check
      run: cargo fmt -- --check

  docs:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable
    - name: Build documentation
      run: |
        cargo doc --no-deps --release
    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc
        publish_branch: gh-pages
